@startuml
'https://plantuml.com/class-diagram

class Yayo {
+ Yayo(Proveedor proveedor, Invitado invitado)
+ contarChistes(): Chiste
+ todosLosChistes(): List<Chiste>
+ mejoresChistesr(int cantidad) :List<Chiste>
}

class Chiste {
- String categoria;
- String setup;
- String delive
- int puntaje
+ Chiste(String categoria, String delivery, String setup)
+  aplicarPuntaje(int puntaje): int
+  tieneCategoria(String c) :boolean
+  esMalo(): boolean

}

interface Proveedor {
+ solicitarChiste(String categoria, String idioma): Chiste
}

interface Invitado {
+ puntuar(Chiste chiste): int
}

interface Tiempo {
+ obtenerDiaDeHoy(): int
}

class TiempoProductivo implements Tiempo {
+ obtenerDiaDeHoy(): int
}

class ProveedorWeb implements Proveedor {
+ solicitarChiste(String categoria, String idioma): Chiste
}

class InvitadoRandom implements Invitado {
+ puntuar(Chiste chiste): int
}

Yayo *-left- Chiste: 0..*
Yayo -down-> Invitado
Yayo -right->Proveedor
Yayo ..> Tiempo

@enduml